artifact_location: file:///d:/OneDrive - Prodapt Solutions Private Limited/prodapt/pioneer/llmops/labs/Lab1-LLMOps-Pipeline/mlflow/521750072828646810
creation_time: 1765381498712
experiment_id: '521750072828646810'
last_update_time: 1765381498712
lifecycle_stage: active
name: LLMOps_Prompt_Registry
