artifact_uri: file:///d:/OneDrive - Prodapt Solutions Private Limited/prodapt/pioneer/llmops/labs/Lab1-LLMOps-Pipeline/mlflow/521750072828646810/22b1fa9640ac4bbdb9ced69e44112ddf/artifacts
end_time: 1765381500060
entry_point_name: ''
experiment_id: '521750072828646810'
lifecycle_stage: active
run_id: 22b1fa9640ac4bbdb9ced69e44112ddf
run_name: prompt-v1.0.0
source_name: ''
source_type: 4
source_version: ''
start_time: 1765381499990
status: 3
tags: []
user_id: sivasubramanian.v
